excel:
  name: 'futureloan_api_test.xlsx'

host: 'http://8.129.91.152:8766/futureloan'

tester:
  mobile_phone: '18584086762'
  pwd: 'yey1201abc'

administrator:
  mobile_phone: '18581512456'
  pwd: 'yey1201abc'

investor:
  mobile_phone: '15883308876'
  pwd: 'yey1201abc'

investor_id:
tester_id: 739
administrator_id: 0201938